// USED EXCEL TO ANALYZE THE DATA AND UPLOADED THE DATA IN SNOWFLAKE//

// CREATED  DATABASE AND SCHEMA RESPECTIVELY//

CREATE DATABASE credit_card_analytics;
CREATE SCHEMA raw;
USE DATABASE credit_card_analytics;
USE SCHEMA raw;
