CREATE TABLE credit_card_analytics.raw.raw_transactions (
  unnamed_0 INTEGER,
  trans_date_trans_time TIMESTAMP,
  cc_num STRING,
  merchant STRING,
  category STRING,
  amt FLOAT,
  first STRING,
  last STRING,
  gender STRING,
  street STRING,
  city STRING,
  state STRING,
  zip STRING,
  lat FLOAT,
  long FLOAT,
  city_pop INTEGER,
  job STRING,
  dob DATE,
  trans_num STRING,
  unix_time INTEGER,
  merch_lat FLOAT,
  merch_long FLOAT,
  is_fraud INTEGER,
  merch_zipcode STRING
);
