// USED KAGGLE DATASET - CREDIT CARD ANALYSIS //

// RAW FILE ---> CSV ---> 500K RECORDS //

// LOADED THE DATA USING SNOWFLAKE//

SELECT COUNT(*)
FROM RAW_TRANSACTIONS;

SELECT *
FROM RAW_TRANSACTIONS
LIMIT 10;
