SELECT COUNT(AMT) AS TOTAL_AMT 
FROM  RAW_TRANSACTIONS
WHERE GENDER = 'F';

SELECT DISTINCT FIRST , AMT FROM RAW_TRANSACTIONS
WHERE JOB = 'Musician' 
ORDER BY FIRST;

SELECT * FROM RAW_TRANSACTIONS;

// TO CHECK NO Negative amount//
  
SELECT AMT FROM RAW_TRANSACTIONS
WHERE AMT < 0;
