// ALTERING THE COLUMN NAMES TO VALID COLUMN_NAMES//

ALTER TABLE RAW_TRANSACTIONS
RENAME COLUMN FIRST TO FIRST_NAME;

ALTER TABLE RAW_TRANSACTIONS
RENAME COLUMN LAST TO LAST_NAME;

ALTER TABLE RAW_TRANSACTIONS
RENAME COLUMN LONG TO LONGITUDE;

ALTER TABLE RAW_TRANSACTIONS
RENAME COLUMN JOB TO JOB_ROLE;

ALTER TABLE RAW_TRANSACTIONS
RENAME COLUMN CITY POP TO CITY_POP;

Describe table RAW_TRANSACTIONS;

// TO CHECK NULL VALUES//

SELECT 
    COUNT(*) AS TOTAL_ROWS,
    COUNT(CASE WHEN CC_NUM IS NULL THEN 1 END ) AS transactions_id_nulls,
    COUNT(CASE WHEN TRANS_DATE_TRANS_TIME IS NULL THEN 1 END ) AS TRANS_DATE_TRANS_TIME_NULLS,
    COUNT(CASE WHEN MERCHANT IS NULL THEN 1 END ) AS MERCHANT_NULLS,
    COUNT (CASE WHEN CATEGORY IS NULL THEN 1 END ) AS CATEGORY_NULLS,
    COUNT(CASE WHEN AMT IS NULL THEN 1 END  ) AS AMT_NULL,
    COUNT(CASE WHEN FIRST_NAME IS NULL THEN 1 END  )AS FIRST_NULL,
    COUNT (CASE WHEN LAST_NAME IS NULL THEN 1 END ) AS LAST_NULL,
    COUNT (CASE WHEN GENDER IS NULL THEN 1 END ) AS GENDER_NULL,
    COUNT (CASE WHEN STREET IS NULL THEN 1 END ) AS STREET_NULL,
    COUNT (CASE WHEN CITY IS NULL THEN 1 END ) AS CITY_NULL,
    COUNT (CASE WHEN STATE IS NULL THEN 1 END ) AS STATE_NULL,
    COUNT (CASE WHEN ZIP IS NULL THEN 1 END ) AS ZIP_NULL,
    COUNT (CASE WHEN LAT IS NULL THEN 1 END ) AS LAT_NULL,
    COUNT (CASE WHEN LONGITUDE IS NULL THEN 1 END ) AS LONG_NULL,
    COUNT (CASE WHEN CITY_POP IS NULL THEN 1 END ) AS CITY_POP_NULL,
    COUNT (CASE WHEN JOB_ROLE IS NULL THEN 1 END ) AS JOB_NULL,
    COUNT (CASE WHEN DOB IS NULL THEN 1 END ) AS DOB_NULL,
    COUNT (CASE WHEN TRANS_NUM IS NULL THEN 1 END ) AS TRANS_NUM_NULL,
    COUNT (CASE WHEN UNIX_TIME IS NULL THEN 1 END) AS UNIX_TIME_NULL,
    COUNT (CASE WHEN  MERCH_LAT IS NULL THEN 1 END ) AS MERC_LAT_NULL,
    COUNT (CASE WHEN MERCH_LONG IS NULL THEN 1 END ) AS MERCH_LONG_NULL,
    COUNT (CASE WHEN IS_FRAUD IS NULL THEN 1 END ) AS IS_FRAUD_NULL,
    COUNT (CASE WHEN MERCH_ZIPCODE IS NULL THEN 1 END ) AS MERCH_ZIPCODE
    
From raw_transactions;

SELECT 
    IS_FRAUD,
    COUNT(*) AS TOTAL_TRANSACTIONS,
    COUNT_IF(MERCH_ZIPCODE IS NULL) AS NULL_ZIPCODES,
    ROUND( COUNT_IF (MERCH_ZIPCODE IS NULL) *100 / COUNT(*), 2 )AS NULL_PERCENTAGE
    FROM RAW_TRANSACTIONS
    GROUP BY IS_FRAUD;

// TO FIND DUPLICATE ROWS// EXPECTED RESULTS - NO RESULTS // ACTUAL RESULT - NO RESULTS//


SELECT * , 
    COUNT(*) AS DUPLICATE_ROWS,
    FROM RAW_TRANSACTIONS
    GROUP BY ALL 
    HAVING COUNT(*) > 1;

// TO CHECK DUPLICATE ROWS IN TRANSACTIONS// EXPECTED RESULTS - All Transactions are unique // ACTUAL RESULT - No results//

  
SELECT TRANS_NUM , 
    COUNT(TRANS_NUM) AS DUPLICATE_TRAN_NUM
    FROM RAW_TRANSACTIONS
    GROUP BY TRANS_NUM
    HAVING COUNT(*) > 1;

// TO CHECK DUPLICATE ROWS IN CREDIT_CARD// EXPECTED RESULTS - MULTIPLE ENTRIES // ACTUAL RESULT - MULTIPLE ENTRIES//

SELECT CC_NUM, 
    COUNT(CC_NUM) AS DUPLICATE_CC_NUM
    FROM RAW_TRANSACTIONS
    GROUP BY CC_NUM
    HAVING COUNT(*) > 1 ;

// TO CHECK DOUBLE SWIPPED TRANSACTIONS// EXPECTED RESULTS - NA // ACTUAL RESULTS - NA//
  
SELECT 
    COUNT(*) AS TOTAL_ROWS,
    COUNT( DISTINCT TRANS_NUM) AS UNIQUE_TRANSACTIONS
    FROM RAW_TRANSACTIONS;

// Changing UNNAMED TO TRANS_ID //

ALTER TABLE RAW.RAW_TRANSACTIONS
RENAME COLUMN UNNAMED_0 TO ROW_ID;

// INVALID NEGATIVE TRANSACTION AMOUNTS //

SELECT *
FROM RAW_TRANSACTIONS
WHERE AMT <= 0;

// FUTURE DATES  - NO DATES EXISTS //

SELECT TRANS_DATE_TRANS_TIME 
FROM RAW_TRANSACTIONS
WHERE TRANS_DATE_TRANS_TIME > CURRENT_TIMESTAMP();

// EARLIEST AND LATEST TRANS// // EARLIEST 2019-01-01 00:00:18.000// LATEST 2019-08-05 09:56:57.000 //

SELECT 
MIN(TRANS_DATE_TRANS_TIME),
MAX(TRANS_DATE_TRANS_TIME)
FROM RAW_TRANSACTIONS; 

SELECT GENDER , 
COUNT(*) AS TOTAL 
FROM RAW_TRANSACTIONS
GROUP BY GENDER;
