//To follow data warehousing best practices, the original RAW_TRANSACTIONS table was preserved without modification. 
Data validation and exploratory analysis were performed on the raw dataset, while all transformation, standardization, 
and cleaning operations were applied to a separate CLEAN_TRANSACTIONS table. 
This approach maintains the integrity of the raw source data and enables reproducible ETL processing//

SELECT COUNT(*) 
FROM CLEAN_TRANSACTIONS;

DESCRIBE TABLE CLEAN_TRANSACTIONS;

ALTER TABLE CLEAN_TRANSACTIONS
RENAME COLUMN ROW_ID TO TRANSACTION_ID;

ALTER TABLE CLEAN_TRANSACTIONS
RENAME COLUMN TRANS_DATE_TRANS_TIME TO TRANACTION_TIMESTAMP;

ALTER TABLE CLEAN_TRANSACTIONS
RENAME COLUMN CC_NUM TO CREDIT_CARD_NUMBER;

SELECT MERCHANT , COUNT(*) FROM CLEAN_TRANSACTIONS
GROUP BY MERCHANT;

ALTER TABLE CLEAN_TRANSACTIONS
RENAME COLUMN MERCHANT TO MERCHANT_NAME;

ALTER TABLE CLEAN_TRANSACTIONS
RENAME COLUMN AMT TO TRANSACTION_AMOUNT;

ALTER TABLE CLEAN_TRANSACTIONS
RENAME COLUMN STREET TO CUSTOMER_STREET;

ALTER TABLE CLEAN_TRANSACTIONS
RENAME COLUMN CITY TO CUSTOMER_CITY;

ALTER TABLE CLEAN_TRANSACTIONS
RENAME COLUMN STATE TO CUSTOMER_STATE;

ALTER TABLE CLEAN_TRANSACTIONS
RENAME COLUMN ZIP TO CUSTOMER_ZIPCODE;

ALTER TABLE CLEAN_TRANSACTIONS
RENAME COLUMN LAT TO CUSTOMER_LAT;

ALTER TABLE CLEAN_TRANSACTIONS
RENAME COLUMN LONGITUDE TO CUSTOMER_LONG;

ALTER TABLE CLEAN_TRANSACTIONS
RENAME COLUMN CITY_POP TO CUSTOMER_CITY_POPULATION;

ALTER TABLE CLEAN_TRANSACTIONS
RENAME COLUMN JOB_ROLE TO CUSTOMER_JOB_ROLE;

ALTER TABLE CLEAN_TRANSACTIONS
RENAME COLUMN DOB TO CUSTOMER_DOB;

ALTER TABLE CLEAN_TRANSACTIONS
RENAME COLUMN TRANS_NUM TO TRANSACTION_NUMBER;

ALTER TABLE CLEAN_TRANSACTIONS
RENAME COLUMN UNIX_TIME TO UNIX_TIMESTAMP;

ALTER TABLE CLEAN_TRANSACTIONS
RENAME COLUMN MERCH_LAT TO MERCHANT_LATITUDE;

ALTER TABLE CLEAN_TRANSACTIONS
RENAME COLUMN MERCH_LONG TO MERCHANT_LONGITUDE;

ALTER TABLE CLEAN_TRANSACTIONS
RENAME COLUMN IS_FRAUD TO FRAUD_FLAG;

ALTER TABLE CLEAN_TRANSACTIONS
RENAME COLUMN MERCH_ZIPCODE TO MERCHANT_ZIPCODE;

ALTER TABLE CLEAN_TRANSACTIONS
RENAME COLUMN GENDER TO CUSTOMER_GENDER;

ALTER TABLE CLEAN_TRANSACTIONS
RENAME COLUMN CATEGORY TO TRANSACTION_CATEGORY;

DESCRIBE TABLE CLEAN_TRANSACTIONS;

ALTER TABLE CLEAN_TRANSACTIONS
RENAME COLUMN FIRST_NAME TO CUSTOMER_FIRST_NAME;

ALTER TABLE CLEAN_TRANSACTIONS
RENAME COLUMN LAST_NAME TO CUSTOMER_LAST_NAME;

SELECT DISTINCT TRANSACTION_CATEGORY 
FROM CLEAN_TRANSACTIONS
ORDER BY TRANSACTION_CATEGORY;

UPDATE CLEAN_TRANSACTIONS
SET TRANSACTION_CATEGORY = 
CASE 
    WHEN TRANSACTION_CATEGORY = 'entertainment' THEN 'Entertainment'
    WHEN TRANSACTION_CATEGORY = 'food_dining' THEN 'Food & Dining'
    WHEN TRANSACTION_CATEGORY = 'gas_transport' THEN 'Fuel & Transport'
    WHEN TRANSACTION_CATEGORY = 'grocery_net' THEN 'Grocery(Online)'
    WHEN TRANSACTION_CATEGORY = 'grocery_pos' THEN 'Grocery(In-Store)'
    WHEN TRANSACTION_CATEGORY = 'health_fitness' THEN 'Health & Fitness'
    WHEN TRANSACTION_CATEGORY = 'home' THEN 'Home'
    WHEN TRANSACTION_CATEGORY = 'kids_pets' THEN 'Kids & Pets'
    WHEN TRANSACTION_CATEGORY = 'misc_net' THEN 'Miscellaneous(Online)'
    WHEN TRANSACTION_CATEGORY = 'misc_pos' THEN 'Miscellaneous(In-Store)'
    WHEN TRANSACTION_CATEGORY = 'personal_care' THEN 'Personal Care'  
    WHEN TRANSACTION_CATEGORY = 'shopping_net' THEN 'Shopping(Online)'
    WHEN TRANSACTION_CATEGORY = 'shopping_pos' THEN 'Shopping(In-Store)'
    WHEN TRANSACTION_CATEGORY = 'travel' THEN 'Travel' 
    ELSE TRANSACTION_CATEGORY
END;
    
SELECT CUSTOMER_GENDER , COUNT(*) FROM CLEAN_TRANSACTIONS
GROUP BY CUSTOMER_GENDER;

UPDATE CLEAN_TRANSACTIONS
SET CUSTOMER_GENDER = 
CASE 
    WHEN CUSTOMER_GENDER = 'Female' THEN 'Female'
    WHEN CUSTOMER_GENDER = 'MALE' THEN 'Male'
    ELSE CUSTOMER_GENDER
END;

