CREATE OR REPLACE TABLE 
DIM_CATEGORY(
    CATEGORY_KEY INT,
    TRANSACTION_CATEGORY VARCHAR(100)
    
    );

INSERT INTO DIM_CATEGORY
    SELECT ROW_NUMBER() OVER(ORDER BY TRANSACTION_CATEGORY) AS CATEGORY_KEY,
    TRANSACTION_CATEGORY
    FROM 
        (SELECT DISTINCT TRANSACTION_CATEGORY
        FROM CLEAN_TRANSACTIONS);


SELECT * FROM DIM_CATEGORY
ORDER BY CATEGORY_KEY ASC;
