CREATE OR REPLACE TABLE 
DIM_CUSTOMER (
    CUSTOMER_KEY INT,
    CREDIT_CARD_NUMBER NUMBER,
    CUSTOMER_FIRST_NAME VARCHAR(100),
    CUSTOMER_LAST_NAME VARCHAR(100),
    CUSTOMER_GENDER VARCHAR(20),
    CUSTOMER_DOB DATE,
    CUSTOMER_JOB_ROLE VARCHAR(200),
    CUSTOMER_STREET VARCHAR(200),
    CUSTOMER_CITY VARCHAR(100),
    CUSTOMER_STATE VARCHAR(50),
    CUSTOMER_ZIPCODE NUMBER,
    CUSTOMER_CITY_POPULATION NUMBER,
    CUSTOMER_LAT FLOAT,
    CUSTOMER_LONG FLOAT);

INSERT INTO DIM_CUSTOMER
SELECT
    ROW_NUMBER() OVER (ORDER BY CREDIT_CARD_NUMBER) AS CUSTOMER_KEY,
    CREDIT_CARD_NUMBER,
    CUSTOMER_FIRST_NAME,
    CUSTOMER_LAST_NAME,
    CUSTOMER_GENDER,
    CUSTOMER_DOB,
    CUSTOMER_JOB_ROLE,
    CUSTOMER_STREET,
    CUSTOMER_CITY,
    CUSTOMER_STATE,
    CUSTOMER_ZIPCODE,
    CUSTOMER_CITY_POPULATION,
    CUSTOMER_LAT,
    CUSTOMER_LONG
FROM 
(  SELECT DISTINCT
     
CREDIT_CARD_NUMBER,
CUSTOMER_FIRST_NAME,
CUSTOMER_LAST_NAME,
CUSTOMER_GENDER,
CUSTOMER_DOB,
CUSTOMER_JOB_ROLE,
CUSTOMER_STREET,
CUSTOMER_CITY,
CUSTOMER_STATE,
CUSTOMER_ZIPCODE,
CUSTOMER_CITY_POPULATION,
CUSTOMER_LAT,
CUSTOMER_LONG
FROM CLEAN_TRANSACTIONS
);
    
SHOW COLUMNS IN TABLE CLEAN_TRANSACTIONS;

SELECT COUNT(*) FROM DIM_CUSTOMER;
// 938//
SELECT COUNT(DISTINCT CREDIT_CARD_NUMBER)
FROM CLEAN_TRANSACTIONS;
// 938//
