CREATE TABLE DIM_MERCHANT
(
    MERCHANT_KEY INT,
    MERCHANT_NAME VARCHAR(255)
);

INSERT INTO DIM_MERCHANT

SELECT
    ROW_NUMBER() OVER (ORDER BY MERCHANT_NAME) AS MERCHANT_KEY,
    MERCHANT_NAME
FROM
(
    SELECT DISTINCT MERCHANT_NAME
    FROM CLEAN_TRANSACTIONS
);
