CREATE OR REPLACE TABLE FACT_TRANSACTIONS
(
    TRANSACTION_ID INT,

    DATE_KEY INT,
    CUSTOMER_KEY INT,
    MERCHANT_KEY INT,
    CATEGORY_KEY INT,

    TRANSACTION_AMOUNT DECIMAL(10,2),

    FRAUD_FLAG INT,

    UNIX_TIMESTAMP BIGINT,

    MERCHANT_LATITUDE FLOAT,
    MERCHANT_LONGITUDE FLOAT,
    MERCHANT_ZIPCODE NUMBER
);

INSERT INTO FACT_TRANSACTIONS

SELECT

    CT.TRANSACTION_ID,

    DD.DATE_KEY,

    DC.CUSTOMER_KEY,

    DM.MERCHANT_KEY,

    DCA.CATEGORY_KEY,

    CT.TRANSACTION_AMOUNT,

    CT.FRAUD_FLAG,

    CT.UNIX_TIMESTAMP,

    CT.MERCHANT_LATITUDE,

    CT.MERCHANT_LONGITUDE,

    CT.MERCHANT_ZIPCODE

FROM CLEAN_TRANSACTIONS CT

INNER JOIN DIM_DATE DD
ON CAST(CT.TRANSACTION_TIMESTAMP AS DATE)=DD.FULL_DATE

INNER JOIN DIM_CUSTOMER DC
ON CT.CREDIT_CARD_NUMBER=DC.CREDIT_CARD_NUMBER

INNER JOIN DIM_MERCHANT DM
ON CT.MERCHANT_NAME=DM.MERCHANT_NAME

INNER JOIN DIM_CATEGORY DCA
ON CT.TRANSACTION_CATEGORY=DCA.TRANSACTION_CATEGORY;
