//  VIEW 1 //

CREATE OR REPLACE VIEW VW_FRAUD_TRANSACTIONS AS 

SELECT 
    FT.TRANSACTION_ID,
    DD.FULL_DATE,
    DC.CUSTOMER_FIRST_NAME,
    DC.CUSTOMER_LAST_NAME,
    DCA.TRANSACTION_CATEGORY,
FROM FACT_TRANSACTIONS FT

JOIN DIM_DATE DD 
ON FT.DATE_KEY = DD.DATE_KEY

JOIN DIM_CUSTOMER DC 
ON FT.CUSTOMER_KEY = DC.CUSTOMER_KEY

JOIN DIM_CATEGORY DCA
ON FT.CATEGORY_KEY = DCA.CATEGORY_KEY

JOIN DIM_MERCHANT DM 
ON FT.MERCHANT_KEY = DM.MERCHANT_KEY

WHERE FT.FRAUD_FLAG = 1;

SELECT COUNT(*) FROM VW_FRAUD_TRANSACTIONS
LIMIT 10;

// VIEW 2 //
  
CREATE OR REPLACE VIEW VW_CUSTOMER_SPENDING AS 
SELECT
    DC.CUSTOMER_KEY,
    DC.CUSTOMER_FIRST_NAME,
    DC.CUSTOMER_LAST_NAME,
    COUNT(*) AS TOTAL_TRANSACTIONS,
    SUM(FT.TRANSACTION_AMOUNT) AS TOTAL_SPENT,
    AVG(FT.TRANSACTION_AMOUNT) AS AVERAGE_TRANSACTION_VALUE,
    MAX(FT.TRANSACTION_AMOUNT) AS MAXIMUM_TRANSACTION_VALUE    
FROM FACT_TRANSACTIONS FT 

JOIN DIM_CUSTOMER DC
ON FT.CUSTOMER_KEY = DC.CUSTOMER_KEY

GROUP BY 
    DC.CUSTOMER_KEY,
    DC.CUSTOMER_FIRST_NAME,
    DC.CUSTOMER_LAST_NAME;
    
SELECT * FROM VW_CUSTOMER_SPENDING
ORDER BY MAXIMUM_TRANSACTION_VALUE DESC;

//VIEW 3//

CREATE OR REPLACE VIEW VW_CATEGORY_ANALYSIS AS
SELECT 
    DCA.TRANSACTION_CATEGORY,
    COUNT (*) AS TOTAL_TRANSACTIONS,
    SUM(FT.TRANSACTION_AMOUNT) AS TOTAL_SALES,
    AVG(FT.TRANSACTION_AMOUNT) AS AVG_SALES,
    MAX(FT.TRANSACTION_AMOUNT) AS MAX_SALES,
    SUM(FT.FRAUD_FLAG) AS FRAUD_CASES
FROM FACT_TRANSACTIONS FT
JOIN DIM_CATEGORY DCA
ON DCA.CATEGORY_KEY = FT.CATEGORY_KEY
GROUP BY 
    DCA.TRANSACTION_CATEGORY;

// VIEW 4 //

CREATE OR REPLACE VIEW VW_MERCHANT_ANALYSIS AS
SELECT
    DM.MERCHANT_NAME,
    COUNT (*) AS TOTAL_TRANSACTION,
    SUM(FT.TRANSACTION_AMOUNT) AS TOTAL_REVENUE,
    AVG(FT.TRANSACTION_AMOUNT) AS AVG_REVENUE,
    SUM(FT.FRAUD_FLAG) AS FRAUD_CASES
FROM FACT_TRANSACTIONS FT 
JOIN DIM_MERCHANT DM
ON DM.MERCHANT_KEY = FT.MERCHANT_KEY
GROUP BY 
    DM.MERCHANT_NAME;

// VIEW 5 //

CREATE OR REPLACE VIEW VW_MONTHLY_TRANSACTION_SUMMARY AS
SELECT 
    DD.YEAR,
    DD.MONTH_NAME,
    COUNT(*) AS TOTAL_TRANSACTIONS,
    SUM(FT.TRANSACTION_AMOUNT) AS TOTAL_REVENUE,
    SUM(FT.FRAUD_FLAG) AS FRAUD_TRANSACTIONS
FROM FACT_TRANSACTIONS FT 
JOIN DIM_DATE DD
ON DD.DATE_KEY = FT.DATE_KEY
GROUP BY 
    DD.YEAR,
    DD.MONTH_NAME,
    DD.MONTH
ORDER BY
    DD.YEAR,
    DD.MONTH;

// All VIEWS EXECUTED//

SELECT * 
FROM VW_CATEGORY_ANALYSIS
LIMIT 5;

SELECT *
FROM VW_CUSTOMER_SPENDING
LIMIT 5;

SELECT *
FROM VW_FRAUD_TRANSACTIONS
LIMIT 5;

SELECT *
FROM VW_MERCHANT_ANALYSIS
LIMIT 5;

SELECT *
FROM VW_MONTHLY_TRANSACTION_SUMMARY
LIMIT 5;







